import express from "express";
import {createDoc, login ,getAllDoctors} from "../controllers/adminController.js";
import upload from "../middlewares/multer.js";
import authAdminMiddleware from "../middlewares/auth.js";
import {changeAvailability} from "../controllers/doctorController.js";
const adminRouter =express.Router();
adminRouter.route('/admin').post(authAdminMiddleware,upload.single('image'),createDoc);
adminRouter.route('/admin/login').post(login);
adminRouter.route('/admin').get(authAdminMiddleware,getAllDoctors);
adminRouter.route('/admin/doctor/:id').patch(authAdminMiddleware,changeAvailability);
export default adminRouter;
